### ISSUE TITLE
ELK

### ISSUE THREAD

**Issue by fatefly** [Kn0wl3dge/mozitools#2]

**Comment by fatefly** [comment]
ELK_HOSTS = "https://admin:admin@opendistro-opendistro-es-client-service " \
            ".monitoring.svc.cluster.local:9200"
可以用本地的ELK吗？

**Comment by kn0wl3dge** [comment]
I'm not sure to understand your question.
You can use any deployed ELK stack (local or remote) as soon as the elastic service can be contacted by the tool.
